-- TelePlay global player data. Access is intentionally server-only: RLS is
-- enabled with no anon/authenticated policies; the Edge Function uses its
-- server-side database connection after Telegram initData verification.

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  telegram_id text not null unique,
  username text not null default '',
  first_name text not null default '',
  avatar text not null default '',
  created_at bigint not null,
  last_active bigint not null,
  records_json jsonb not null default '{}'::jsonb,
  statistics_json jsonb not null default '{}'::jsonb,
  state_json jsonb not null default '{}'::jsonb
);

create table if not exists public.progress (
  player_id text primary key references public.players(telegram_id) on delete cascade,
  level integer not null default 1 check (level between 1 and 100),
  xp bigint not null default 0 check (xp >= 0),
  total_xp bigint not null default 0 check (total_xp >= 0),
  rank text not null default 'rookie',
  streak_json jsonb not null default '{}'::jsonb,
  achievements_json jsonb not null default '[]'::jsonb,
  mastery_json jsonb not null default '{}'::jsonb,
  titles_json jsonb not null default '{}'::jsonb,
  challenges_json jsonb not null default '{}'::jsonb,
  updated_at bigint not null
);

create table if not exists public.economy (
  player_id text primary key references public.players(telegram_id) on delete cascade,
  coins bigint not null default 0 check (coins >= 0),
  gems bigint not null default 0 check (gems >= 0),
  updated_at bigint not null
);

create table if not exists public.inventory (
  player_id text primary key references public.players(telegram_id) on delete cascade,
  profile_json jsonb not null default '{}'::jsonb,
  games_json jsonb not null default '{}'::jsonb,
  updated_at bigint not null
);

create table if not exists public.transactions (
  id text primary key,
  player_id text not null references public.players(telegram_id) on delete cascade,
  currency_type text not null check (currency_type in ('coins', 'gems')),
  type text not null check (type in ('earn', 'spend')),
  amount bigint not null,
  balance_after bigint not null check (balance_after >= 0),
  source text not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at bigint not null
);

create table if not exists public.game_sessions (
  id text primary key,
  player_id text not null references public.players(telegram_id) on delete cascade,
  game_id text not null,
  started_at bigint,
  finished_at bigint,
  score bigint not null default 0,
  duration bigint not null default 0,
  result_json jsonb not null default '{}'::jsonb,
  created_at bigint not null
);

create table if not exists public.analytics_events (
  id text primary key,
  player_id text not null references public.players(telegram_id) on delete cascade,
  event text not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at bigint not null
);

create table if not exists public.admin_actions (
  id text primary key,
  admin_id text not null,
  role text not null,
  target_player_id text,
  action text not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at bigint not null
);

create index if not exists idx_players_last_active on public.players(last_active desc);
create index if not exists idx_players_level on public.progress(level desc);
create index if not exists idx_transactions_player on public.transactions(player_id, created_at desc);
create index if not exists idx_sessions_player on public.game_sessions(player_id, created_at desc);
create index if not exists idx_events_player on public.analytics_events(player_id, created_at desc);
create index if not exists idx_admin_actions_target on public.admin_actions(target_player_id, created_at desc);

alter table public.players enable row level security;
alter table public.progress enable row level security;
alter table public.economy enable row level security;
alter table public.inventory enable row level security;
alter table public.transactions enable row level security;
alter table public.game_sessions enable row level security;
alter table public.analytics_events enable row level security;
alter table public.admin_actions enable row level security;
